CREATE TABLE IF NOT EXISTS `__PREFIX__sync_login` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`uid` int(11) unsigned NOT NULL COMMENT '用户ID',
    `unionid` varchar(50) DEFAULT '' COMMENT '第三方UNIONID',
	`openid` varchar(50) DEFAULT '' COMMENT '第三方OPENID',
    `openname` varchar(50) DEFAULT '' COMMENT '第三方会员昵称',
    `platform` varchar(30) DEFAULT '' COMMENT '第三方应用',
    `apptype` varchar(50) DEFAULT '' COMMENT '应用所属类型',
	`access_token` varchar(255) NOT NULL,
    `refresh_token` varchar(255) DEFAULT 'RefreshToken',
    `expires_in` int(10) unsigned DEFAULT '0' COMMENT '有效期',
    `create_time` int(10) unsigned DEFAULT NULL COMMENT '创建时间',
    `update_time` int(10) unsigned DEFAULT NULL COMMENT '更新时间',
    `login_time` int(10) unsigned DEFAULT NULL COMMENT '登录时间',
    `expire_time` int(10) unsigned DEFAULT NULL COMMENT '过期时间',
	`status` tinyint(2) NOT NULL DEFAULT '1' COMMENT '状态描述',
    PRIMARY KEY (`id`),
    UNIQUE KEY `platform` (`platform`,`openid`),
    KEY `uid` (`uid`,`platform`),
    KEY `unionid` (`platform`,`unionid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT='第三方登录表';